import { LOGIN } from "../constants/action-types";
import { ADD_USER_DATA } from "../constants/action-types";
import { CHANGE_LOGIN_BUTTON_STATUS } from "../constants/action-types";
import { ADD_FORM_ERROR } from "../constants/action-types";
import { CLEAR_FORM_ERROR } from "../constants/action-types";
import { CHANGE_FRIEND_NAV_HEADER } from "../constants/action-types";
import { CHANGE_FRIEND_OR_REQUEST } from "../constants/action-types";
import { ADD_FRIENDS_AND_REQUESTS } from "../constants/action-types";
import { REMOVE_FRIEND_REQUEST } from "../constants/action-types";
import { ADD_FRIEND } from "../constants/action-types";
import { OPEN_CONVERSATION } from "../constants/action-types";
import { REMOVE_FRIEND } from "../constants/action-types";

export const login = loggedIn => ({ type: LOGIN, payload: loggedIn});
export const addUserData  = userData => ({ type: ADD_USER_DATA, payload: userData});
export const changeLoginButtonStatus  = loginButtonStatus => ({ type: CHANGE_LOGIN_BUTTON_STATUS, payload: loginButtonStatus});
export const addFormError = formError => ({ type: ADD_FORM_ERROR, payload: formError });
export const clearFormError = formError => ({ type: CLEAR_FORM_ERROR, payload: formError });
export const changeFriendNavHeader = friendNavHeaderStatus => ({ type: CHANGE_FRIEND_NAV_HEADER, payload: friendNavHeaderStatus });
export const changeFriendOrRequest = friendOrRequest => ({ type: CHANGE_FRIEND_OR_REQUEST, payload: friendOrRequest });
export const addFriendsAndRequests = friendsAndRequests => ({ type: ADD_FRIENDS_AND_REQUESTS, payload: friendsAndRequests });
export const removeFriendRequest = friendRequest => ({ type: REMOVE_FRIEND_REQUEST, payload: friendRequest });
export const addFriend = friendRequest => ({ type: ADD_FRIEND, payload: friendRequest });
export const openConversation = conversationParams => ({ type: OPEN_CONVERSATION, payload: conversationParams });
export const removeFriend = friend => ({ type: REMOVE_FRIEND, payload: friend });
