export const LOGIN = "LOGIN";
export const ADD_USER_DATA = "ADD_USER_DATA";
export const CHANGE_LOGIN_BUTTON_STATUS = "CHANGE_LOGIN_BUTTON_STATUS";
export const ADD_FORM_ERROR = "ADD_FORM_ERROR";
export const CLEAR_FORM_ERROR = "CLEAR_FORM_ERROR";
